### ISSUE TITLE
Add tracker for wallets

### ISSUE THREAD

**Issue by milkyklim** [igorline/chzwzrds#103]
This is more solid issue: 
- [ ] track all pawheads
- [ ] track wizards wallet movement 
- [ ] track total energy per user
